### ISSUE TITLE
Requires pry, but pry is missing from Gemspec dependencies

### ISSUE THREAD

**Issue by mnquintana** [izuzak/github-labeler#1]
Thanks for releasing this @izuzak! :beers: 

Just tried to run `github-labeler` on a fresh Ruby 2.2.1, and got this error:

```
/Users/mnq2/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- pry (LoadError)
    from /Users/mnq2/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/mnq2/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/github-labeler-0.1.0/bin/github-labeler:5:in `<top (required)>'
    from /Users/mnq2/.rbenv/versions/2.2.1/bin/github-labeler:23:in `load'
    from /Users/mnq2/.rbenv/versions/2.2.1/bin/github-labeler:23:in `<main>'
```

Installing `pry` locally fixed this. Looks like `pry` [is required for the binary here](https://github.com/izuzak/github-labeler/blob/master/bin/github-labeler#L5), but isn't listed in the runtime dependencies in the Gemspec: https://github.com/izuzak/github-labeler/blob/master/github-labeler.gemspec#L14-L15

**Comment by izuzak** [comment]
Ahh, that require can be removed -- I'm not using it in the file anymore. Thanks for noticing, I'll get that fixed.
